# Materials service base URL — override in consuming application
server.url=http://localhost:8080/
quarkus.rest-client.material-client.url=${server.url}
quarkus.rest-client.product-client.url=${server.url}
quarkus.rest-client.bom-client.url=${server.url}

# Quarkus
quarkus.http.port=8081

# Logging
quarkus.log.level=INFO
quarkus.log.category."me.amiralles.materials.client".level=DEBUG
quarkus.mcp.server.traffic-logging.enabled=true
quarkus.mcp.server.traffic-logging.text-limit=5000

##  MCP  server
quarkus.mcp.server.sse.root-path=/mcp

quarkus.http.auth.permission.authenticated.paths=/mcp/*
quarkus.http.auth.permission.authenticated.policy=authenticated

quarkus.oidc.tenant-paths=/mcp/*
quarkus.oidc.token.audience=quarkus-mcp-alpha
quarkus.oidc.resource-metadata.enabled=true
quarkus.oidc.resource-metadata.force-https-scheme=false

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:6274

quarkus.keycloak.devservices.realm-path=alpha-realm.json
quarkus.keycloak.devservices.realm-name=alpha
quarkus.keycloak.devservices.create-client=false


